module.exports = {
  elements: {
    parseResult: 'parseResult',
    category: 'category',
    resource: 'resource',
    copy: 'copy',
    dataStructure: 'dataStructure',
    resourcePrototype: 'resourcePrototype',
    transition: 'transition',
    hrefVariables: 'hrefVariables',
    member: 'member',
    string: 'string',
    array: 'array',
    object: 'object',
    httpRequest: 'httpRequest',
    httpResponse: 'httpResponse',
    httpTransaction: 'httpTransaction',
    httpHeaders: 'httpHeaders',
    asset: 'asset',
    ref: 'ref',
  },
  categoryClasses: {
    api: 'api',
    resourceGroup: 'resourceGroup',
    dataStructures: 'dataStructures',
    resourcePrototypes: 'resourcePrototypes',
    messageBody: 'messageBody',
  },
};
