module.exports = {
  elements: {
    parseResult: 'parseResult',
    category: 'category',
    resource: 'resource',
    copy: 'copy',
    dataStructure: 'dataStructure',
    resourcePrototype: 'resourcePrototype',
    transition: 'transition',
    hrefVariables: 'hrefVariables',
    member: 'member',
    boolean: 'boolean',
    string: 'string',
    number: 'number',
    file: 'file',
    array: 'array',
    object: 'object',
    enum: 'enum',
    select: 'select',
    option: 'option',
    httpRequest: 'httpRequest',
    httpResponse: 'httpResponse',
    httpTransaction: 'httpTransaction',
    httpHeaders: 'httpHeaders',
    asset: 'asset',
    ref: 'ref',
    sourceMap: 'sourceMap',
  },
  categoryClasses: {
    api: 'api',
    resourceGroup: 'resourceGroup',
    dataStructures: 'dataStructures',
    resourcePrototypes: 'resourcePrototypes',
    messageBody: 'messageBody',
    messageBodySchema: 'messageBodySchema',
  },
};
