# My API

In Language Server mode dependencies loop should not raise an error

# Data Structures

## Admin (User)
+ a
+ b

## User (Admin)
+ c
+ d

# Admins [/admins]

## List [GET]

+ Response 200 (application/json)
    + Attributes (Admin)
