# My API

In Language Server mode duplicated named type should not raise an error

# Data Structures

## User
+ a
+ b

## User
+ c
+ d

# GET /user

+ Response 200 (application/json)
    + Attributes (User)
