# My API

In Language Server mode invalid Attributes section should not raise an error

# Data Structures

# User (object

+ name
+ email

# GET /user
+ Response 200 (application/json)
    + Attributes (User)
