# API name

In Language Server mode invalid Action section should not raise an error

# Resource Prototypes

## NotFound

+ Response 404

# Group Users

## Users [/users]

## GET (Not

+ Response 200
