# API name

In Language Server mode invalid Named Action section should not raise an error

# Resource Prototypes

## NotFound

+ Response 404

# Group Users

## Users [/users]

## List all users [GET] (Not

+ Response 200
