# My API

In Language Server named type based on schema type should not raise an error

# Data Structures

## Admin (User)
+ a
+ b

# Schema Structures

# User

+ Schema

        {
          "type": "object"
        }

+ Body

        {}

# GET /admin

+ Response 200 (application/json)
    + Attributes (Admin)
