# My API

In Language Server complex property of named type based on schema type should not raise an error

# Data Structures

## Admin
+ user (User)
    + info

# Schema Structures

# User

+ Schema

        {
          "type": "object"
        }

+ Body

        {}

# GET /admin

+ Response 200 (application/json)
    + Attributes (Admin)
