# My API

In Language Server schema type without schema should not raise an error

# Schema Structures

## User
+ Body

        {}

# GET /user

+ Response 200 (application/json)
    + Attributes (User)
