# My API

In Language Server mode action element without response should generate httpTransaction.

# Create user [POST /user]

+ Request (application/json)
  + Attributes
    + name: John (string, required) - User name
