# My API

In Language Server mode unknown property type with nested property should not raise an error

# GET /admin

+ Response 200 (application/json)
    + Attributes
      + result (Admin)
        + additionalInfo (string)
