# My API

In Language Server mode unknown base type should not raise an error

# Data Structures

## Admin (User)
+ a
+ b

# Admins [/admins]

## List [GET]

+ Response 200 (application/json)
    + Attributes (Admin)
